micronaut:
  application:
    name: vote-backend
  # expose Swagger OpenAPI
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  http:
    services:
      githubv3:
        url: "https://api.github.com"

  security:
    authentication: cookie
    token:
      propagation.enabled: true
      jwt:
        signatures:
          secret:
            generator:
              secret: 'Dv2dqx6dW0w21U9IFA7t0eOjkMB0bf6k' # 256bit entropy. Not necessarily base64 - any string will do.
    oauth2:
      clients:
        microsoft:
          enabled: false
          grant-type: authorization_code
          client-id: 28b292b8-b5fd-41be-8b1b-dda96485fb78
          client-secret: 25fda8b2-1ede-42c6-82ea-0ff5dbb000c6
          redirect-uri: 'http://localhost:8080/oauth/callback/microsoft'
          scopes:
            - 'User.Read'
          authorization:
            url: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize'
          token:
            url: 'https://login.microsoftonline.com/common/oauth2/v2.0/token'
            auth-method: client_secret_basic
          client-credentials:






        github:
          grant-type: authorization_code
          client-id: e02a6af391ffc5a454da
          client-secret: d886b6e471ac63dfb1316eb884a759e4449c9025
          scopes:
            - 'user:email'
            - 'read:user'
          authorization:
            url: 'https://github.com/login/oauth/authorize'
          token:
            url: 'https://github.com/login/oauth/access_token'
            auth-method: client_secret_post
          redirect-uri: http://localhost:8080/oauth/callback/githubv3



        google:
          enabled: false
          client-id: 857066476501-khdp7f8snlte69tu62mgj2lbibg8j80i.apps.googleusercontent.com
          client-secret: XXy2i7yjRAopJMIU-YAZSeBI

    endpoints:
      logout:
        get-allowed: true
    reject-not-found: false


jackson:
  bean-introspection-module: true
  serialization:
    # Configure Jackson to represent Instant as human readable dates rather than epoch second.nanosecond
    write-dates-as-timestamps: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/vote?ssl=false
    driverClassName: org.postgresql.Driver
    username: vote
    password: gJnUwvJ&EbeP
    dialect: POSTGRES

# database migration
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

# expose /m path for debug and monitoring
endpoints:
  all.path: /m
  flyway:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  loggers:
    enabled: true

# alternative way to specify log level
logger:
  levels:
    io:
      micronaut:
        security:
          authentication: DEBUG
          oauth2: TRACE
        http:
          server:
            netty: DEBUG