create table PARTICIPANT_LIST
(
    ID          int generated by default as identity not null primary key,
    TITLE       varchar(100) not null,
    DESCRIPTION varchar(1000)
);

create table PARTICIPANT
(
    ID          varchar(100) not null primary key,
    LIST_ID     int not null,
    VALID_FROM  timestamp    not null,
    VALID_TILL  timestamp,
    constraint fk_participants_list
        foreign key(LIST_ID)
            references PARTICIPANT_LIST(ID)
);

create table PARTICIPANT_LIST_VERSION
(
    LIST_ID int not null,
    VERSION int not null,
    SINCE   timestamp,
    constraint pk_plv
        primary key (LIST_ID, VERSION)
);